### PR TITLE
Enable memcache/redis code to be used simultaneously

### PR DESCRIPTION
**Pull request by jshore1296**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/131)

### CODE REVIEW

**Review by daboyuka — APPROVED** [review]
:lgtm: but tests crapped out

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/131#-:-MeeqMqYCwKn0ldmhGRc:bltkjw2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Review by daboyuka — APPROVED** [review]
Also needs Jira issue, and let's try [check]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/131#-:-MeetP9DBXdTTygeYlA7:bq1h7kn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Comment by pendo-ops** [comment]
Okay, All checks were run. Did not encounter any errors.

**Review by daboyuka — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/131#-:-MefSsW00MncJCpS4Y_W:b3sq3yz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Comment by pendo-ops** [comment]
Branch enable-memcache deleted

**Pull request merged**
