### PR TITLE
APP-37135 don't hardcode cloud task http content type header

### PR DESCRIPTION
**Pull request by mccall114**
Removing the hardcoded `Content-Type` header for http target tasks and will pass that in from the pendo-appengine side (in my http target stuff & feedback). I'll have a pendo-appengine PR to update that.

Also fixing the param `queueName` to have the correct name `serviceAccount`.

---
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/118)

### CODE REVIEW

**Review by jshore1296 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/118)* status: all files reviewed, 1 unresolved discussion (waiting on @gr-eg and @mccall114)

*[a discussion](https://reviewable.io/reviews/pendo-io/appwrap/118#-MI4Oymg1bflDVQSZVKz:-MI4OymhE9h-0PBkWQJY:b5ybf51) (no related file):*
We need to make sure that anywhere in appengine that currently depends on this is updated as well.  Greg probably will have a better idea.

---

**Comment by mccall114** [comment]
*[a discussion](https://reviewable.io/reviews/pendo-io/appwrap/118#-MI4Oymg1bflDVQSZVKz:-MI4rXFTBYSyAML3gqG5:bywe9y7) (no related file):*
<details><summary><i>Previously, jshore1296 wrote…</i></summary><blockquote>

We need to make sure that anywhere in appengine that currently depends on this is updated as well.  Greg probably will have a better idea.
</blockquote></details>

Yeah it looks like just in 1 place for feedback: [diff for future PR](https://github.com/pendo-io/pendo-appengine/compare/APP-37137-cloud-task-http-headers). @gr-eg this look right to you?

---

**Review by gr-eg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/118)* status: all files reviewed, 1 unresolved discussion (waiting on @jshore1296 and @mccall114)

*[a discussion](https://reviewable.io/reviews/pendo-io/appwrap/118#-MI4Oymg1bflDVQSZVKz:-MI4sssSEm8gQuCCNv30:b7dz4dg) (no related file):*
<details><summary><i>Previously, mccall114 (Maggie Templeton) wrote…</i></summary><blockquote>

Yeah it looks like just in 1 place for feedback: [diff for future PR](https://github.com/pendo-io/pendo-appengine/compare/APP-37137-cloud-task-http-headers). @gr-eg this look right to you?
</blockquote></details>

Yep that looks fine :+1: 

---

**Review by jshore1296 — APPROVED** [review]
:lgtm: [merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/118#-:-MI4wb-34EMgbd6MM52W:bi2vj75)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-37135](https://pendo-io.atlassian.net/browse/APP-37135): Jira Issue APP-37135: Changed to Resolved


Branch APP-37135-cloud-task-http-content-type deleted

**Pull request merged**
