### PR TITLE
Count ancestor as a filter

### PR DESCRIPTION
**Pull request by jshore1296**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/129)

### CODE REVIEW

**Review by malenchite — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Comment by malenchite** [comment]
[merge]

**Comment by jshore1296** [comment]
[check]

**Comment by pendo-ops** [comment]
Okay, All checks were run. Did not encounter any errors.

**Comment by malenchite** [comment]
[merge]

**Comment by malenchite** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch index-bug deleted

**Pull request merged**
