### PR TITLE
Connect to local redis/memcache if running locally

### PR DESCRIPTION
**Pull request by jshore1296**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/157)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[259b5cd](https://github.com/pendo-io/appwrap/pull/157/commits/259b5cd4156f073584c47277595b580a84e9cf25)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[7b0bf0a](https://github.com/pendo-io/appwrap/pull/157/commits/7b0bf0a0b12acba05fa366196c2148fbc8127860)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[6b10d9b](https://github.com/pendo-io/appwrap/pull/157/commits/6b10d9bc09b57d9a97e361cfaeecbf97098c19a6)

**Review by ewtroan — APPROVED** [review]
[merge]

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/157#-:-NY4OPbq6bYa6c1aY_uh:b3sq3yz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Comment by pendo-ops** [comment]
Branch local-memcache deleted

**Pull request merged**
