### PR TITLE
APP-63594 Make WrapBackgroundContextWithStackdriverLogger testable

### PR DESCRIPTION
**Pull request by malenchite**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/145)

### CODE REVIEW

**Review by mkj-pendo — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @malenchite)

**Comment by mkj-pendo** [comment]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-63593](https://pendo-io.atlassian.net/browse/APP-63593): Invalid state 'Backlog' for merge into master

**Review by mkj-pendo — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @malenchite)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-63594](https://pendo-io.atlassian.net/browse/APP-63594): Jira Issue APP-63594: Changed to Resolved


Branch sci-app-63594 deleted

**Pull request merged**
