### PR TITLE
upgrade datastore to v1.20.0

### PR DESCRIPTION
**Pull request by sgp**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/179)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[a90a300](https://github.com/pendo-io/appwrap/pull/179/commits/a90a300ad5938561cbd1c213f12a888248ec0b4e)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[4b975ba](https://github.com/pendo-io/appwrap/pull/179/commits/4b975baa390e6af44accedbcfc203425d55a703d)

**Review by DP19 — APPROVED** [review]
merge

**Comment by pendo-ops** [comment]
Branch cloud-datastore-1.20.0 deleted

**Pull request merged**
