### PR TITLE
Failover function for Memorystore

### PR DESCRIPTION
**Pull request by jbornemann**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/121)

### CODE REVIEW

**Review by DP19 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/121)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jbornemann and @jshore1296)

___
*[memorystore.go, line 93 at r1](https://reviewable.io/reviews/pendo-io/appwrap/121#-MUAOOkS0VlcZxAXNSJC:-MUAOOkS0VlcZxAXNSJD:b-pensdj) ([raw file](https://github.com/pendo-io/appwrap/blob/8e9d67430e90fd758fca3d947ee41434cd1fa2b1/memorystore.go#L93)):*
> ```Go
> 
> func (rci *redisClientImplementation) Failover(ctx context.Context) error {
> 	return rci.client.ClusterFailover(ctx).Err()
> ```

Do we know how this acts vs `gcloud redis instances failover` specifically with --data-protection-mode?

**Review by jshore1296 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/121)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @DP19)

___
*[memorystore.go, line 93 at r1](https://reviewable.io/reviews/pendo-io/appwrap/121#-MUAOOkS0VlcZxAXNSJC:-MUAQ2F551fluN7cCZkQ:bwxd1jd) ([raw file](https://github.com/pendo-io/appwrap/blob/8e9d67430e90fd758fca3d947ee41434cd1fa2b1/memorystore.go#L93)):*
<details><summary><i>Previously, DP19 (David Pait) wrote…</i></summary><blockquote>

Do we know how this acts vs `gcloud redis instances failover` specifically with --data-protection-mode?
</blockquote></details>

Yeah, if possible, I would much rather use the cloud API to initiate the failover.

**Comment by jbornemann** [comment]
> > _[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/121)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jbornemann and @jshore1296)
> 
> _[memorystore.go, line 93 at r1](https://reviewable.io/reviews/pendo-io/appwrap/121#-MUAOOkS0VlcZxAXNSJC:-MUAOOkS0VlcZxAXNSJD:b-pensdj) ([raw file](https://github.com/pendo-io/appwrap/blob/8e9d67430e90fd758fca3d947ee41434cd1fa2b1/memorystore.go#L93)):_
> 
> > ```go
> > func (rci *redisClientImplementation) Failover(ctx context.Context) error {
> > 	return rci.client.ClusterFailover(ctx).Err()
> > ```
> 
> Do we know how this acts vs `gcloud redis instances failover` specifically with --data-protection-mode?

Seems to only issue "cluster failover", which waits for data replication.

**Comment by jbornemann** [comment]
Changed to just expose the failover function on our Redis API service.

**Review by jshore1296 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/121)* status: all files reviewed, 1 unresolved discussion (waiting on @DP19)

**Review by DP19 — APPROVED** [review]
[merge]

**Comment by pendo-ops** [comment]
Branch jb-memstore-failover deleted

**Pull request merged**
