### PR TITLE
APP-76987 Remove net/context in appwrap

### PR DESCRIPTION
**Pull request by daboyuka**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/152)

### CODE REVIEW

**Review by mattlovedev — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daboyuka)

**Review by dkindel — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daboyuka)

**Review by dkindel — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/152#-:-NOzqLpD-Q6Qoo9R1_I4:b3sq3yz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daboyuka)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-76987](https://pendo-io.atlassian.net/browse/APP-76987): Jira Issue APP-76987: Changed to Resolved


Branch dab-remove-netcontext deleted

**Pull request merged**
