### PR TITLE
upgrade datastore libraries and remove vendoring

### PR DESCRIPTION
**Pull request by sgp**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/173)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[ded1bc4](https://github.com/pendo-io/appwrap/pull/173/commits/ded1bc457fdfc49838ed16407bf1be1dcc5f9f02)
[b41f59d](https://github.com/pendo-io/appwrap/pull/173/commits/b41f59d159deeab67ad745b82ede8ac4aed35fcb)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[729faa7](https://github.com/pendo-io/appwrap/pull/173/commits/729faa751276675ae4c75831f1e77a6680332523)
[7579154](https://github.com/pendo-io/appwrap/pull/173/commits/7579154d117c734c01794fd64e99176ac8853e72)

**Comment by DP19** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch merge failed. Required status check "pendo.io/code-review" is pending.

**Review by DP19 — APPROVED** [review]

**Comment by DP19** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch sgp-upgrade-datastore deleted

**Pull request merged**
