### PR TITLE
DEVOPS-3940 - instate dual log labels

### PR DESCRIPTION
**Pull request by nateturner**
Appwrap changes for log labels

---
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/146)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[eda3c5b](https://github.com/pendo-io/appwrap/pull/146/commits/eda3c5b006eec2a69ef10e6392b52f6dc0d220ee)
[8e93c38](https://github.com/pendo-io/appwrap/pull/146/commits/8e93c38bc3780fc8172d6ce046656486c5fbe264)
[0f66f5a](https://github.com/pendo-io/appwrap/pull/146/commits/0f66f5a11eb2f7106cc131637beff4c4641ecff4)
[6e7db2b](https://github.com/pendo-io/appwrap/pull/146/commits/6e7db2b93d93806be5733c06918162daee42ab32)
[cbd4560](https://github.com/pendo-io/appwrap/pull/146/commits/cbd4560ac88dbb38d45bd5e3d95da45e648fcda1)

**Review by DP19 — CHANGES_REQUESTED** [review]

**Review by DP19 — APPROVED** [review]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues need reviews:
* [DEVOPS-3940](https://pendo-io.atlassian.net/browse/DEVOPS-3940): Unknown value for the Data Privacy Review field.

**Comment by DP19** [comment]
[check]

**Comment by pendo-ops** [comment]
Okay, All checks were run. Did not encounter any errors.

**Comment by DP19** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [DEVOPS-3940](https://pendo-io.atlassian.net/browse/DEVOPS-3940): Resolved


Branch nate_intern deleted

**Pull request merged**
