### PR TITLE
use xxhash instead of crc

### PR DESCRIPTION
**Pull request by jshore1296**
xxhash provides a better key distribution.  crc32 was leading
to some weird results

---
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/134)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[736dbb5](https://github.com/pendo-io/appwrap/pull/134/commits/736dbb5cd0777042182e902dd855d67f0eeec3bf)

**Review by sgp — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Review by sgp — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/134#-:-MknHfEUDRronn6qNCOu:b3sq3yz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Comment by pendo-ops** [comment]
Branch better-hash-memcache deleted

**Pull request merged**
