### PR TITLE
add flex-compatible implementation of AppengineInfo interface

### PR DESCRIPTION
**Pull request by ewtroan**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/8)

### CODE REVIEW

**Comment by jenshevach** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[appinfoflex.go, line 13 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7emBxaGorhfvz2nr3a:-L7emBxaGorhfvz2nr3b:bosdxcz) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfoflex.go#L13)):*
> ```Go
> 	"strings"
> 
> 	//"cloud.google.com/go/compute/metadata"
> ```

Why commented and not removed? for later, perhaps?

---

*[appinfoflex.go, line 38 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7emp8pmgserHnkFLPk:-L7emp8pmgserHnkFLPl:b-k0te64) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfoflex.go#L38)):*
> ```Go
> 
> func (ai AppengineInfoFlex) ModuleHostname(version, module, app string) (string, error) {
> 	// it's not at all clear this is right...
> ```

Did it work when tested on bundler? How can we verify it is correct?

---

*[appinfostd.go, line 11 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7eliFq0B8xWJPBYzzd:-L7eliFq0B8xWJPBYzze:bf8jv5z) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfostd.go#L11)):*
> ```Go
> )
> 
> type AppengineInfoFromContext struct {
> ```

If this now represents the appengine info for std instances, should it be named as such?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/appwrap/8)*

**Comment by ewtroan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[appinfoflex.go, line 38 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7emp8pmgserHnkFLPk:-L7gTYhb9cuTVK4KWCR7:bkp9bur) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfoflex.go#L38)):*
<details><summary><i>Previously, jenshevach wrote…</i></summary><blockquote>

Did it work when tested on bundler? How can we verify it is correct?
</blockquote></details>

This is a tough one. It

1. probably doesn't actually work on flex because modules aren't externally addressable
2. isn't used on flex, it's only actually called on standard

I know this answer isn't good, so I'll make it return an error instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/appwrap/8)*

**Comment by ewtroan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[appinfoflex.go, line 13 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7emBxaGorhfvz2nr3a:-L7gUVMptMWhWgyUFlnS:b-896fix) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfoflex.go#L13)):*
<details><summary><i>Previously, jenshevach wrote…</i></summary><blockquote>

Why commented and not removed? for later, perhaps?
</blockquote></details>

Done.

---

*[appinfoflex.go, line 38 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7emp8pmgserHnkFLPk:-L7gUW-KJK35MnHUcfet:b-896fix) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfoflex.go#L38)):*
<details><summary><i>Previously, ewtroan (Erik Troan) wrote…</i></summary><blockquote>

This is a tough one. It

1. probably doesn't actually work on flex because modules aren't externally addressable
2. isn't used on flex, it's only actually called on standard

I know this answer isn't good, so I'll make it return an error instead.
</blockquote></details>

Done.

---

*[appinfostd.go, line 11 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7eliFq0B8xWJPBYzzd:-L7gUUYIS3f-RedGEt5R:b-896fix) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfostd.go#L11)):*
<details><summary><i>Previously, jenshevach wrote…</i></summary><blockquote>

If this now represents the appengine info for std instances, should it be named as such?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/appwrap/8)*

**Comment by jenshevach** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[appinfoflex.go, line 38 at r1](https://reviewable.io:443/reviews/pendo-io/appwrap/8#-L7emp8pmgserHnkFLPk:-L7iWZ-EV6-XDOSH8YEX:bp75rch) ([raw file](https://github.com/pendo-io/appwrap/blob/1a8323f0c4740f350124d15ac2ae2a6d180f1885/appinfoflex.go#L38)):*
<details><summary><i>Previously, ewtroan (Erik Troan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"supported"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pendo-io/appwrap/8)*

**Comment by jenshevach** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pendo-io/appwrap/8#-:-L7iivW1EmFwHLbtIPxY:bnfp4nl)*

**Comment by jenshevach** [comment]
[merge]

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pendo-io/appwrap/8#-:-L7ij-hC0LqFH9JX2CRt:b3sq3yz)*

**Pull request merged**
