### PR TITLE
APP-36912 Checking for nil ancestor

### PR DESCRIPTION
**Pull request by coltonbotta**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/116)

### CODE REVIEW

**Review by larajohn — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/116#-:-MHwaUVU9TXucDqv7Bf_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hoffman29)

**Review by hoffman29 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/116)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hoffman29 — APPROVED** [review]
:lgtm: [merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/116#-:-MIQarcd0NzL737JSW6b:bi2vj75)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-36912](https://pendo-io.atlassian.net/browse/APP-36912): Jira Issue APP-36912: Changed to Resolved


Branch cgb-app-36192-ancestor deleted

**Pull request merged**
