### PR TITLE
update to go 1.21 and use circle cis go 1.21 image

### PR DESCRIPTION
**Pull request by DP19**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/171)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[027e0e4](https://github.com/pendo-io/appwrap/pull/171/commits/027e0e42de357a56fcc2d5705d6147bfab248b7c)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[31986d1](https://github.com/pendo-io/appwrap/pull/171/commits/31986d147fa974fe82bf807cdd25d46b90f128df)

**Review by JamesBalazs — APPROVED** [review]
LGTM, looks like this just needs a jira ref added to the commit

**Comment by DP19** [comment]
> LGTM, looks like this just needs a jira ref added to the commit

We don't require it in public repos, even though it runs 🙄

**Comment by JamesBalazs** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch gcr-io-eol deleted

**Pull request merged**
