### PR TITLE
Enable tracing

### PR DESCRIPTION
**Pull request by jshore1296**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)

### CODE REVIEW

**Review by sgp — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: all files reviewed, 3 unresolved discussions (waiting on @jshore1296)

*[a discussion](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJPqUy6C983Y1o1zPe:-MUJPqUy6C983Y1o1zPf:b-puqhag) (no related file):*
We should use `const`s to declare all of our metric and label names and put them in one place rather than scattered through the code.

---
___
*[aeloggingstackdriver.go, line 180 at r1](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJNpcd3vdvJVX5zl6s:-MUJNpcd3vdvJVX5zl6t:b-vhybjq) ([raw file](https://github.com/pendo-io/appwrap/blob/ed6c3cc7789e8ef37379c566d825c3ff7ce26144/aeloggingstackdriver.go#L180)):*
> ```Go
> 
> 	if traceId == "" {
> 		traceId = fmt.Sprintf("%d", rand.Int63())
> ```

For things like this, I prefer `strconv.FormatInt(rand.Int63(), 10)` because parsing `%d` is a waste.
___
*[clouddatastore.go, line 358 at r1](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJP-Ni2mEnQeP8SVq1:-MUJP-Ni2mEnQeP8SVq2:b-7lvmk6) ([raw file](https://github.com/pendo-io/appwrap/blob/ed6c3cc7789e8ef37379c566d825c3ff7ce26144/clouddatastore.go#L358)):*
> ```Go
> 	}
> 
> 	err := ct.transaction.DeleteMulti(keys)
> ```

Q: how does this trace/span work if you can't get to the context used by the transaction?
___
*[clouddatastore.go, line 204 at r2](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJQFN248nx69oQ4AsS:-MUJQFN37XkT9JuZcLLt:bwbrand) ([raw file](https://github.com/pendo-io/appwrap/blob/bb711edb981790514824af4b5a1d421a1305aeae/clouddatastore.go#L204)):*
> ```Go
> 
> 	span.AddAttributes(trace.Int64Attribute("num-keys", int64(len(keys))))
> ```

Nice catch to make this always set the label. :100:

**Review by jshore1296 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: all files reviewed, 3 unresolved discussions (waiting on @sgp)

*[a discussion](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJPqUy6C983Y1o1zPe:-MUJW8CG2GQPQuZahkSj:b-896fix) (no related file):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

We should use `const`s to declare all of our metric and label names and put them in one place rather than scattered through the code.
</blockquote></details>

Done.

---
___
*[aeloggingstackdriver.go, line 180 at r1](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJNpcd3vdvJVX5zl6s:-MUJRaAe1BXj06q6J8LQ:b-896fix) ([raw file](https://github.com/pendo-io/appwrap/blob/ed6c3cc7789e8ef37379c566d825c3ff7ce26144/aeloggingstackdriver.go#L180)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

For things like this, I prefer `strconv.FormatInt(rand.Int63(), 10)` because parsing `%d` is a waste.
</blockquote></details>

Done.
___
*[clouddatastore.go, line 358 at r1](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJP-Ni2mEnQeP8SVq1:-MUJR6GF0xSAI_oPY-gL:b-fzar2o) ([raw file](https://github.com/pendo-io/appwrap/blob/ed6c3cc7789e8ef37379c566d825c3ff7ce26144/clouddatastore.go#L358)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

Q: how does this trace/span work if you can't get to the context used by the transaction?
</blockquote></details>

Good question!  Look at the code for `RunInTransaction` - the context we pass in to the `ct.transaction` is the same context that's stored in `ct.ctx`.  You have to trace it a bit.  `cds.ctx` becomes `c`, which then gets passed into the timeout func and becomes `tctx`

**Review by sgp — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: all files reviewed, 5 unresolved discussions (waiting on @jshore1296)

___
*[clouddatastore.go, line 358 at r1](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJP-Ni2mEnQeP8SVq1:-MUJZ9kRBHdHt_rj8caf:b-bu9gqz) ([raw file](https://github.com/pendo-io/appwrap/blob/ed6c3cc7789e8ef37379c566d825c3ff7ce26144/clouddatastore.go#L358)):*
<details><summary><i>Previously, jshore1296 wrote…</i></summary><blockquote>

Good question!  Look at the code for `RunInTransaction` - the context we pass in to the `ct.transaction` is the same context that's stored in `ct.ctx`.  You have to trace it a bit.  `cds.ctx` becomes `c`, which then gets passed into the timeout func and becomes `tctx`
</blockquote></details>

:upside_down_face: That's not opaque at all! But I'm OK with this magic. :see_no_evil: 
___
*[clouddatastore.go, line 524 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJZxH0DqVSEvPCqznQ:-MUJZxH0DqVSEvPCqznR:bz6y97r) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/clouddatastore.go#L524)):*
> ```Go
> 
> func (cdq CloudDatastoreQuery) GetAll(dst interface{}) ([]*DatastoreKey, error) {
> 	_, span := trace.StartSpan(cdq.ctx, "pendo.io/datastore/query/get-all")
> ```

Missed a spot on the `const`'ing
___
*[memorystore.go, line 463 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJ_DoJD6uvBsct69hM:-MUJ_DoK1stX0Id0sqVF:b-jx0gj9) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L463)):*
> ```Go
> 		defer span.End()
> 
> 		span.AddAttributes(trace.StringAttribute(traceLabelFirstKey, shardKeys[0]))
> ```

Nit: `shardKeys[0]` feels like a `panic` waiting to happen. (Ideally, we'd never call `addMultiForShard` with `len(shardKeys) == 0`, but ...
___
*[memorystore.go, line 619 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJa5zDBd1xkgEiV-Ip:-MUJa5zDBd1xkgEiV-Iq:beyymgv) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L619)):*
> ```Go
> 				haveErrors = true
> 			}
> 		}()
> ```

:astonished: FYI - ... we just fire deletes off into the ether and don't wait for the go funcs to return? (This is informational because it's not part of this issue to fix it, but ... umm.)
___
*[memorystore.go, line 689 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJaMKr11i76vzbTmaA:-MUJaMKr11i76vzbTmaB:buk3m4g) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L689)):*
> ```Go
> 		defer span.End()
> 
> 		span.AddAttributes(trace.StringAttribute(traceLabelFirstKey, shardKeys[0]))
> ```

Nit: `shardKeys[0]` feels like a `panic` waiting to happen. (Ideally, we'd never call `getMultiForShard` with `len(shardKeys) == 0`, but ...
___
*[memorystore.go, line 835 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJaRIA79EqaYyzx04r:-MUJaRIA79EqaYyzx04s:b3kpjv0) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L835)):*
> ```Go
> 		defer span.End()
> 
> 		span.AddAttributes(trace.StringAttribute(traceLabelFirstKey, shardKeys[0]))
> ```

Nit: `shardKeys[0]` feels like a `panic` waiting to happen. (Ideally, we'd never call `setMultiForShard` with `len(shardKeys) == 0`, but ...

**Review by jshore1296 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @jshore1296 and @sgp)

___
*[clouddatastore.go, line 524 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJZxH0DqVSEvPCqznQ:-MUJatKK1d0ttyN3ELCy:b-896fix) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/clouddatastore.go#L524)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

Missed a spot on the `const`'ing
</blockquote></details>

Done.
___
*[memorystore.go, line 619 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJa5zDBd1xkgEiV-Ip:-MUJb0D2-X5Lt9AAxuYc:b-2dkm5e) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L619)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

:astonished: FYI - ... we just fire deletes off into the ether and don't wait for the go funcs to return? (This is informational because it's not part of this issue to fix it, but ... umm.)
</blockquote></details>

These aren't goroutines.  I had to encapsulate the call in a synchronous func() for the defer to work properly.

**Review by jshore1296 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @jshore1296 and @sgp)

___
*[memorystore.go, line 463 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJ_DoJD6uvBsct69hM:-MUJbCX16XAjmWTy3Dk1:bvv7jl0) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L463)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

Nit: `shardKeys[0]` feels like a `panic` waiting to happen. (Ideally, we'd never call `addMultiForShard` with `len(shardKeys) == 0`, but ...
</blockquote></details>

We check further down in the function before we call this one, so I think it's fine given the unit testing we've done?  But we can add the check here too I guess.

**Review by sgp — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: all files reviewed, 3 unresolved discussions (waiting on @jshore1296 and @sgp)

___
*[memorystore.go, line 619 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJa5zDBd1xkgEiV-Ip:-MUJbVcY1OnuKxc7WhHu:b7wrotm) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L619)):*
<details><summary><i>Previously, jshore1296 wrote…</i></summary><blockquote>

These aren't goroutines.  I had to encapsulate the call in a synchronous func() for the defer to work properly.
</blockquote></details>

Uh. Huh. That makes sense. I didn't read closely enough!

**Review by sgp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: all files reviewed, 3 unresolved discussions (waiting on @jshore1296)

___
*[memorystore.go, line 463 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJ_DoJD6uvBsct69hM:-MUJbi0rCecmaDbzE7_T:b5vw3y0) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L463)):*
<details><summary><i>Previously, jshore1296 wrote…</i></summary><blockquote>

We check further down in the function before we call this one, so I think it's fine given the unit testing we've done?  But we can add the check here too I guess.
</blockquote></details>

Maybe just return immediately from `add/set/getMultiFromShard` if `len(shardKeys) == 0`. It's kind of defensive programming, I know...

**Review by sgp — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Review by sgp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Review by sgp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123#-:-MUJdZ18-__z9TxzmVgc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Review by jshore1296 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

___
*[memorystore.go, line 463 at r3](https://reviewable.io/reviews/pendo-io/appwrap/123#-MUJ_DoJD6uvBsct69hM:-MUJcU-C1sWwDpJHtBXT:b-8fx2u7) ([raw file](https://github.com/pendo-io/appwrap/blob/3d467d2c6b48f500bdd6a59c6ca8dfd98d9827b2/memorystore.go#L463)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

Maybe just return immediately from `add/set/getMultiFromShard` if `len(shardKeys) == 0`. It's kind of defensive programming, I know...
</blockquote></details>

:+1:

**Review by sgp — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/123#-:-MUKEqJWBVOZ3xKFcRIL:b3sq3yz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Comment by pendo-ops** [comment]
Branch enable-tracing deleted

**Pull request merged**
