### PR TITLE
Better hashing, don't leak connections, encode keys

### PR DESCRIPTION
**Pull request by jshore1296**
- 1000 entries for each server results in a much lower std. dev. for key
  distribution
- we should only create a new client if the discovery endpoint actually
  changes.  Otherwise, we're just leaking connections, since the
  underlying library never closes them.
- memcache has a lot of illegal characters for keys.  just base64 the
  whole thing.  this is silly

---
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/135)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[4b2ac74](https://github.com/pendo-io/appwrap/pull/135/commits/4b2ac74821ac3f5a0b2f2f7e2978f106f72f381b)

**Review by malenchite — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jshore1296)

**Comment by malenchite** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch better-distribution deleted

**Pull request merged**
