### PR TITLE
 APP-74796 Extend logger in appwrap to expose trace ID

### PR DESCRIPTION
**Pull request by daboyuka**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/150)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[0e19358](https://github.com/pendo-io/appwrap/pull/150/commits/0e193586433f13a4235dd886a5768aee48338b5d)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[d7673c6](https://github.com/pendo-io/appwrap/pull/150/commits/d7673c69cd33d9c556fabeeb2641043dfc6f55e0)

**Review by dkindel — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/150#-:-NMjg4ks4NcsEoaC4JAX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daboyuka)

**Review by dkindel — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/150#-:-NMjgtMDBP6CTr7IZvVV:b3sq3yz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daboyuka)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-74796](https://pendo-io.atlassian.net/browse/APP-74796): Jira Issue APP-74796: Changed to Resolved


Branch dab-log-traceid deleted

**Pull request merged**
