### PR TITLE
APP-52770 put all of guide3 delete in a transaction

### PR DESCRIPTION
**Pull request by npersson001**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/142)

### CODE REVIEW

**Review by night2tl — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/142#-:-MvPV_DR6MXxYqrkHiMe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eryous)

**Review by eryous — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/142#-:-MvPct0u4T4kn0SKbOf7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @npersson001)

**Comment by night2tl** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues need reviews:
* [APP-52770](https://pendo-io.atlassian.net/browse/APP-52770): Needs SOC Review

**Comment by night2tl** [comment]
[merge]

**Pull request merged**
