### PR TITLE
Migrate OpenCensus trace implementation to OpenTelemetry

### PR DESCRIPTION
**Pull request by DP19**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/168)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[8e0ce83](https://github.com/pendo-io/appwrap/pull/168/commits/8e0ce8312228f52485374cd3eabec0b197f2fffe)
[608e653](https://github.com/pendo-io/appwrap/pull/168/commits/608e653d0cd225361753cbd25a0a8e606434c605)

**Review by mccall114 — APPROVED** [review]
[merge]

**Comment by pendo-ops** [comment]
Not merging due to label: `wip-do-not-merge`.

**Comment by mccall114** [comment]
[merge]

**Comment by pendo-ops** [comment]
Branch opentelemetry deleted

**Pull request merged**
