### PR TITLE
Memcache - Consistent hashing

### PR DESCRIPTION
**Pull request by jshore1296**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/133)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[b2bb89e](https://github.com/pendo-io/appwrap/pull/133/commits/b2bb89e83a37425525ff60c2aa7776626ff82572)
[f0fd825](https://github.com/pendo-io/appwrap/pull/133/commits/f0fd825420223d95533a4db7db537a246b172249)

**Review by sgp — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/133)* status: all files reviewed, 1 unresolved discussion (waiting on @jshore1296)

___
*[memcached.go, line 402 at r2](https://reviewable.io/reviews/pendo-io/appwrap/133#-Mkn3AyO74fblXzQ-5Bv:-Mkn3AyP0QDSaeb8WX_g:bqimr7t) ([raw file](https://github.com/pendo-io/appwrap/blob/f0fd825420223d95533a4db7db537a246b172249/memcached.go#L402)):*
> ```Go
> 	for _, entry := range s {
> 		b.WriteString(" ")
> 		b.WriteString(fmt.Sprintf("{%d: %s}", entry.hash, entry.addr.String()))
> ```

So close to being `fmt` free! All you have to do is use `strconv.FormatUint(uint64(entry.hash), 10)`...

**Review by sgp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/133)* status: all files reviewed, 1 unresolved discussion (waiting on @jshore1296)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[b2bb89e](https://github.com/pendo-io/appwrap/pull/133/commits/b2bb89e83a37425525ff60c2aa7776626ff82572)
[3b83fda](https://github.com/pendo-io/appwrap/pull/133/commits/3b83fda07cc313b38b14d5a02ba27db36a90ad2c)

**Review by sgp — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/133)* status: all files reviewed, 1 unresolved discussion (waiting on @jshore1296)

**Review by sgp — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/133#-:-MknA9Tl8Wkz748Yqvyv:b3sq3yz)* status: all files reviewed, 1 unresolved discussion (waiting on @jshore1296)

**Comment by pendo-ops** [comment]
Branch new-memcache-shard-algo deleted

**Pull request merged**
