### PR TITLE
replace invalid utf8 characters

### PR DESCRIPTION
**Pull request by DP19**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/appwrap/165)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[f831c07](https://github.com/pendo-io/appwrap/pull/165/commits/f831c070e4a3d462f6fee54979ffd834dbf8ab1b)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[68ecf1f](https://github.com/pendo-io/appwrap/pull/165/commits/68ecf1f64976533eaf6e3bf15f519924fa3d6eb0)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[846558b](https://github.com/pendo-io/appwrap/pull/165/commits/846558be5a6dce0f36ccdf4153ea3c854991fd9f)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[8aa1b33](https://github.com/pendo-io/appwrap/pull/165/commits/8aa1b33b627d0b8d411ca0ffa730429693864e7c)

**Review by sgp — APPROVED** [review]

**Comment by sgp** [comment]
:shipit: [merge]

**Comment by pendo-ops** [comment]
Branch utf8-validation deleted

**Pull request merged**
